In [5]:
import numpy as np

In [16]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

## ayyay[start:end:step] (row selection)

In [17]:
print(arr[0])#print 1st row

[1 2 3 4]


In [18]:
print(arr[-1])#print last row

[13 14 15 16]


In [20]:
print(arr[0:3])#print row 0,1,2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0:3:2])#print row 0,1,2 but skip by 1(every 2nd row)

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [31]:
print(arr[::-1])#print all rows but reversed

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


## column selection

In [33]:
print(arr[:,0])#columns

[ 1  5  9 13]


## selecting thr range

In [39]:
print(arr[:,0:3])#all rows but column range 0,1,2
print("------------------")
print(arr[:,1:3])#all rows but column range 1,2

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
